spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda_engine
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

camunda.bpm.admin-user:
  id: demo
  password: demo